### ISSUE TITLE
FYI: TelegramL

### ISSUE THREAD

**Issue by dsheets** [staceytay/abeetbot#1]
Hi, I just saw your issue on mjambon/atdgen and I thought I'd reach out to let you know about https://github.com/nv-vn/TelegraML/ which is a Telegram API library in OCaml that was recently released. You can get it with `opam` by `opam install telegraml`. Maybe it's not right for your use case but I thought I'd mention it on the off chance you hadn't seen it and it would help you accomplish your goals with OCaml faster. :-)

**Comment by staceytay** [comment]
Hi, cool! I didn't really search for bot libraries for OCaml since I was going to build something simple and I wanted to try out Async and writing a server in OCaml. I don't think I'll use a bot library since I'm mostly done, but thanks for reaching out!
